
datamodule:
  _target_: proteinfoundation.datasets.antibody_data.AntibodyLightningDataModule
  json_path: "./dataset/sabdab_all.json"
  pdb_dir: "./dataset/pdb"
  
  batch_size: 1
  num_workers: 4
  batch_padding: True
  max_length: 800
  
  transforms:
    - _target_: proteinfoundation.datasets.transforms.CoordsToNanometers
    - _target_: proteinfoundation.datasets.transforms.AntibodyMotifMaskTransform