defaults:
  - inference_base
  - generation: motif
  - _self_

#ckpt_path: ./store/antibody_cdr_finetune_motif/checkpoints
ckpt_path: ./checkpoints_laproteina
ckpt_name: LD4_motif_idx_aa.ckpt
#ckpt_name: last.ckpt
autoencoder_ckpt_path: ./checkpoints_laproteina/AE3_motif.ckpt

generation:
  dataset:
    motif_task_name: 5hi4_cdrh3 
    nsamples: 10


    motif_dict_cfg:

      4qci_cdrh3:
        contig_string: "C10-101/L3-9/L11-29/L36-57/L65-72/L74-80/L83-109/L114-129/H1-9/H11-30/H35-59/H62-72/H74-104/13-13/H118-129"
        motif_pdb_path: "./dataset/pdb/4qci.pdb"
        atom_selection_mode: "all_atom"
        motif_only: False

        motif_min_length: 319
        motif_max_length: 319
        segment_order: "C;L;H"


      5hi4_cdrh3:
        contig_string: "B36-104/B108-129/D1-9/D11-30/D35-57/D65-72/D74-109/D114-129/C1-9/C11-30/C35-59/C62-72/C74-104/11-11/C118-129"
        motif_pdb_path: "./dataset/pdb/5hi4.pdb"
        atom_selection_mode: "all_atom"
        motif_only: False
        motif_min_length: 322
        motif_max_length: 322
        segment_order: "B;D;C"

      5l6y_cdrh3:
        contig_string: "C4-70/C86-112/L2-9/L11-29/L36-57/L65-72/L74-80/L83-109/L114-129/H1-9/H11-30/H35-59/H62-72/H74-104/15-15/H118-129"
        motif_pdb_path: "./dataset/pdb/5l6y.pdb"
        atom_selection_mode: "all_atom"
        motif_only: False
        motif_min_length: 324
        motif_max_length: 324
        segment_order: "C;L;H"

      3uzq_cdrh3:
        contig_string: "B299-393/C1-31/C34-57/C65-72/C74-80/C83-109/C114-127/A3-9/A11-30/A35-59/A62-72/A74-104/9-9/A118-128"
        motif_pdb_path: "./dataset/pdb/3uzq.pdb"
        atom_selection_mode: "all_atom"
        motif_only: False
        motif_min_length: 320
        motif_max_length: 320
        segment_order: "B;C;A"

      3h3b_cdrh3:
        contig_string: "B0-177/B181-191/E1-57/E65-72/E74-80/E83-109/E114-127/D2-9/D11-30/D35-59/D62-72/D74-104/13-13/D118-127"
        
        motif_pdb_path: "./dataset/pdb/3h3b.pdb"
        atom_selection_mode: "all_atom"
        motif_only: False
        motif_min_length: 420
        motif_max_length: 420
        segment_order: "B;E;D"


      5j13_cdrh3:
        contig_string: "A28-61/A64-114/A133-156/B1-9/B11-29/B36-57/B65-72/B74-80/B83-110/B113-129/C1-9/C11-30/C35-59/C62-72/C74-104/15-15/C118-129"
        motif_pdb_path: "./dataset/pdb/5j13.pdb"
        atom_selection_mode: "all_atom"
        motif_only: False
        motif_min_length: 342
        motif_max_length: 342
        segment_order: "A;B;C"

      5mes_cdrh3:
        contig_string: "A172-322/L2-9/L11-30/L35-57/L65-72/L74-80/L83-110/L113-129/H1-9/H11-30/H35-59/H62-72/H74-104/12-12/H118-129"
        motif_pdb_path: "./dataset/pdb/5mes.pdb"
        atom_selection_mode: "all_atom"
        motif_only: False
        motif_min_length: 382
        motif_max_length: 382
        segment_order: "A;L;H"

      1ic7_cdrh3:
        contig_string: "Y1-129/L1-107/H1-95/7-7/H103-114"
        motif_pdb_path: "/DATA/disk3/yilin/dyMEAN/all_data/pdb/1ic7.pdb"
        atom_selection_mode: "all_atom"
        motif_only: False
        motif_min_length: 350
        motif_max_length: 350
        segment_order: "Y;L;H"

      4dtg_cdrh3:
        # K Chain (Antigen): K2-K61 (length 60)
        # L Chain (Light): Gaps found at 33, 58-64, 73, 81-82, 110-113
        # H Chain (Heavy): Gaps found at 10, 31-34, 60-61, 73. 
        # CDRH3 sequence "ARLGGYDEGDAMDS" is found perfectly spanning PDB residues H105 to H117 (Length 14).
        contig_string: "K2-61/L1-32/L34-57/L65-72/L74-80/L83-109/L114-129/H1-9/H11-30/H35-59/H62-72/H74-104/14-14/H118-129"
        motif_pdb_path: "./dataset/pdb/4dtg.pdb"
        atom_selection_mode: "all_atom"
        motif_only: False
        # Antigen (60) + L Chain (114) + H Chain Framework (108) + CDRH3 (14) = 296
        motif_min_length: 296
        motif_max_length: 296
        segment_order: "K;L;H"

      3ffd_cdrh3:
        contig_string: "P14-31/B1-9/B11-30/B36-59/B63-72/B74-80/B83-129/A1-9/A11-30/A35-59/A62-72/A74-104/11-11/A118-129"
        motif_pdb_path: "./dataset/pdb/3ffd.pdb"
        atom_selection_mode: "all_atom"
        motif_only: False
        motif_min_length: 254
        motif_max_length: 254
        segment_order: "P;B;A"

  metric:
    compute_designability: True
    compute_codesignability: True   
    compute_novelty_pdb: False
    compute_novelty_afdb: False
    compute_fid: False

  args:
    nsteps: 50
    self_cond: True
    
  model:
    bb_ca:
      simulation_step_params:
        sampling_mode: sc
        sc_scale_noise: 0.1
    local_latents:
      simulation_step_params:
        sampling_mode: sc
        sc_scale_noise: 0.1