
defaults:
  - training_local_latents
  - override /dataset: antibody_custom 
  - override /nn: local_latents_score_nn_160M_motif_idx_aa 
  - _self_


run_name_: antibody_cdr_finetune_motif

hardware:
  accelerator: gpu
  ngpus_per_node_: 1
  nnodes_: 1

trainer:

  strategy: ddp_find_unused_parameters_true



pretrain_ckpt_path: "./checkpoints_laproteina/LD4_motif_idx_aa.ckpt"
autoencoder_ckpt_path: "./checkpoints_laproteina/AE3_motif.ckpt"

training:
  motif_conditioning: True 
  self_cond: True
  p_folding_n_inv_folding_iters: 0.0
  n_recycle: 0


lora:
  r: null
  lora_alpha: 32.0
  lora_dropout: 0.1
  train_bias: none

opt:
  lr: 1.0e-5
  max_epochs: 100
  check_val_every_n_epoch: 1
  
 
  dist_strategy: auto  

 
  accumulate_grad_batches: 8
  val_check_interval: 5000

product_flowmatcher:
  local_latents:
    dim: null
    
force_precision_f32: False